include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - lib/**.g.dart
    - test/**.g.dart
    - flutter_test/**.g.dart
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  errors:
    #
    # Error rules
    #
    avoid_empty_else: error
    avoid_print: error
    avoid_relative_lib_imports: error
    avoid_returning_null_for_future: error
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    avoid_web_libraries_in_flutter: error
    cancel_subscriptions: error
    comment_references: info
    control_flow_in_finally: error
    diagnostic_describe_all_properties: error
    empty_statements: error
    hash_and_equals: error
    invalid_use_of_protected_member: error
    invalid_use_of_visible_for_testing_member: error
    invariant_booleans: info # Wait until https://github.com/dart-lang/linter/issues/1858 is fixed. For now only "info".
    iterable_contains_unrelated_type: error
    list_remove_unrelated_type: error
    literal_only_boolean_expressions: warning
    missing_required_param: error
    missing_return: error
    missing_enum_constant_in_switch: error
    no_adjacent_strings_in_list: error
    no_duplicate_case_values: error
    no_logic_in_create_state: error
    prefer_relative_imports: ignore # Wait until https://github.com/dart-lang/linter/issues/2005 is fixed. For now only "ignore".
    prefer_void_to_null: error
    test_types_in_equals: error
    throw_in_finally: error
    unnecessary_statements: error
    unrelated_type_equality_checks: error
    use_key_in_widget_constructors: error
    valid_regexps: error
    #
    # Style rules
    #
    always_declare_return_types: error
    always_put_required_named_parameters_first: info
    always_require_non_null_named_parameters: error
    annotate_overrides: info
    avoid_as: error
    avoid_bool_literals_in_conditional_expressions: error
    avoid_catching_errors: warning
    avoid_classes_with_only_static_members: error
    avoid_equals_and_hash_code_on_mutable_classes: error
    must_be_immutable: error
    avoid_escaping_inner_quotes: warning
    avoid_implementing_value_types: warning
    avoid_init_to_null: error
    avoid_positional_boolean_parameters: error
    avoid_private_typedef_functions: info
    avoid_redundant_argument_values: error
    avoid_renaming_method_parameters: error
    avoid_return_types_on_setters: error
    avoid_returning_null: error
    avoid_returning_null_for_void: error
    avoid_returning_this: error
    avoid_setters_without_getters: error
    avoid_single_cascade_in_expression_statements: error
    avoid_types_on_closure_parameters: error
    avoid_unnecessary_containers: error
    avoid_unused_constructor_parameters: error
    avoid_void_async: error
    await_only_futures: error
    camel_case_extensions: error
    camel_case_types: error
    # cascade_invocations: error # has false positives
    constant_identifier_names: error
    curly_braces_in_flow_control_structures: error
    directives_ordering: error
    empty_catches: error
    empty_constructor_bodies: error
    # exhaustive_cases: error # unreleased yet
    file_names: error
    implementation_imports: error
    join_return_with_assignment: info
    leading_newlines_in_multiline_strings: error
    library_names: error
    library_prefixes: error
    lines_longer_than_80_chars: error
    missing_whitespace_between_adjacent_strings: error
    # no_default_cases: error # unreleased yet
    no_runtimeType_toString: error
    non_constant_identifier_names: error
    null_closures: error
    omit_local_variable_types: error
    one_member_abstracts: error
    only_throw_errors: error
    overridden_fields: error
    package_prefixed_library_names: error
    parameter_assignments: error
    prefer_adjacent_string_concatenation: error
    prefer_asserts_in_initializer_lists: error
    prefer_collection_literals: error
    prefer_conditional_assignment: error
    prefer_const_constructors: error
    prefer_const_constructors_in_immutables: error
    prefer_const_declarations: error
    prefer_const_literals_to_create_immutables: error
    prefer_constructors_over_static_methods: error
    prefer_contains: error
    prefer_equal_for_default_values: error
    prefer_final_fields: error
    prefer_final_in_for_each: error
    prefer_final_locals: error
    prefer_for_elements_to_map_fromIterable: warning
    prefer_function_declarations_over_variables: error
    prefer_generic_function_type_aliases: error
    prefer_if_elements_to_conditional_expressions: error
    prefer_if_null_operators: error
    prefer_initializing_formals: error
    prefer_inlined_adds: error
    prefer_int_literals: error
    prefer_interpolation_to_compose_strings: error
    prefer_is_empty: error
    prefer_is_not_empty: error
    prefer_is_not_operator: error
    prefer_iterable_whereType: error
    prefer_null_aware_operators: error
    prefer_single_quotes: error
    prefer_spread_collections: error
    prefer_typing_uninitialized_variables: error
    recursive_getters: error
    # sized_box_for_whitespace: error # available in Dart SDK 2.9.0
    slash_for_doc_comments: error
    sort_child_properties_last: error
    sort_constructors_first: error
    sort_unnamed_constructors_first: error
    type_annotate_public_apis: error
    type_init_formals: error
    unawaited_futures: error
    unnecessary_await_in_return: error
    unnecessary_brace_in_string_interps: info
    unnecessary_const: error
    unnecessary_getters_setters: error
    unnecessary_lambdas: error
    unnecessary_new: error
    unnecessary_null_aware_assignments: error
    unnecessary_null_in_if_null_operators: error
    unnecessary_overrides: error
    unnecessary_parenthesis: error
    unnecessary_raw_strings: error
    unnecessary_string_escapes: error
    unnecessary_string_interpolations: error
    unnecessary_this: error
    use_full_hex_values_for_flutter_colors: error
    use_function_type_syntax_for_parameters: error
    # use_is_even_rather_than_modulo: error # unreleased yet
    use_raw_strings: error
    use_rethrow_when_possible: error
    use_setters_to_change_properties: info # Has some false-positive cases. "Info" for now.
    use_string_buffers: error
    use_to_and_as_if_applicable: info
    void_checks: error

linter:
  rules:
    #
    # Error rules
    #
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_web_libraries_in_flutter
    - await_only_futures
    - cancel_subscriptions
    # - close_sinks # not reliable enough
    - comment_references
    - control_flow_in_finally
    - diagnostic_describe_all_properties
    - empty_statements
    - hash_and_equals
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_logic_in_create_state
    - prefer_relative_imports
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    - use_key_in_widget_constructors
    - valid_regexps
    #
    # Style rules
    #
    - always_declare_return_types
    # - always_put_required_named_parameters_first # Flutter's `key` convention doesn't play well with it
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_as
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_implementing_value_types
    - avoid_init_to_null
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - camel_case_extensions
    - camel_case_types
    # - cascade_invocations # has false positives
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    # - exhaustive_cases # unreleased yet
    - file_names
    - implementation_imports
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - lines_longer_than_80_chars
    - missing_whitespace_between_adjacent_strings
    # - no_default_cases # unreleased yet, very important
    - no_runtimeType_toString
    - non_constant_identifier_names
    - null_closures
    - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    # - package_api_docs # requires too much work
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    # - prefer_asserts_with_message # not always possible
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    # - prefer_double_quotes # We prefer single quotes
    - prefer_equal_for_default_values
    # - prefer_expression_function_bodies # Can't enable this since it will highlight almost all `Widget.build`'s
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    # - prefer_foreach # not sure about this one
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    # - prefer_mixin # Can't enable it because many Flutter mixins are implemented as classes
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    # - provide_deprecation_message # not for us
    # - public_member_api_docs # not for us
    - recursive_getters
    # - sized_box_for_whitespace # available in Dart SDK 2.9.0
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    # - unnecessary_final # not for us, conflicts with `prefer_final_locals`
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    # - use_is_even_rather_than_modulo # unreleased yet
    - use_raw_strings
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - void_checks
