name: goloc_editor
description: goloc editor

environment:
  sdk: '>=2.3.0 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.5.9-pre.270'

dependencies:
  flutter:
    sdk: flutter
  csv: ^4.0.3
  provider: ^3.0.0+1
  rxdart: ^0.22.1
  flutter_sticky_header: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/localizations.csv
  # See https://github.com/flutter/flutter/wiki/Desktop-shells#fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono/RobotoMono-Thin.ttf
          weight: 100
        - asset: fonts/RobotoMono/RobotoMono-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/RobotoMono/RobotoMono-Light.ttf
          weight: 300
        - asset: fonts/RobotoMono/RobotoMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/RobotoMono/RobotoMono-Regular.ttf
          weight: 400
        - asset: fonts/RobotoMono/RobotoMono-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: fonts/RobotoMono/RobotoMono-Medium.ttf
          weight: 500
        - asset: fonts/RobotoMono/RobotoMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700
        - asset: fonts/RobotoMono/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic
